name: Build, Test and Deploy

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: kubsu
          POSTGRES_PASSWORD: kubsu
          POSTGRES_DB: kubsu
        ports:
          - "5432:5432"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and test
      uses: docker/build-push-action@v3
      with:
        context: .
        target: builder
        tags: app-builder:latest

  deploy:
    needs: test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME_NEW }}/kubsu-app:latest

    - name: Deploy to server
      run: |
         podman stop kubsu-app || true
         podman rm kubsu-app || true
         podman run -d --name kubsu-app --network host ${{ secrets.DOCKER_HUB_USERNAME_NEW }}/kubsu-app:latest
         echo "Container has been deployed successfully!"
